eclipse-zenoh/zenoh-cpp

.github/workflows/ci.yml
CMakeLists.txt
README.md

Removed zenoh-c download stage from zenoh-cpp building. Now zenoh-cpp build pocedure requires that zenoh-c is already installed and uses it as dependency. This made CMakeLists.txt much simpler and straightforward

switched to find_package in CMakeLists.txt

---

CMakeLists.txt
include/zenohcpp_objects.h
include/zenohcpp_structs.h
tests/closures_func.cpp
tests/closures_obj_ptr_param.cpp
tests/closures_obj_ref_param.cpp
tests/keyexpr.cpp
tests/options.cpp

- function for keyexpr (join, includes, canonize, etc.) added
- GetOptions covered
- tests added
Related to issues:
https://github.com/eclipse-zenoh/zenoh-cpp/issues/12

covered keyexpr api

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

This PR adds the same GitHub issue template as used in all the other Zenoh repositories.

Add issue template

---

examples/universal/z_delete.cxx
examples/universal/z_pub.cxx
examples/universal/z_pub_delete.cxx
examples/universal/z_put.cxx
examples/universal/z_queryable.cxx

The different values and keyexprs are necessary to diffentiate zenoh-c and zenoh-pico examples in https://github.com/ZettaScaleLabs/zenoh-tests

made different string and keyexpr for zenoh-c and zenoh-pico examples

---

README.md

As titled. Remind the users to have Rust toolchain installed. Otherwise, they can not build the tests and examples.

Add a reminder to install Rust

---

include/zenohcxx/impl.hxx

This missing inline was breaking compilation when `zenoh` is included from multiple `.c`, causing the symbol to be defined multiple times, breaking linkage.

Fix missing inline

---

include/zenohcxx/api.hxx
include/zenohcxx/base.hxx
include/zenohcxx/impl.hxx

the  `loan` method is avaliable only if `z_loan` funcion is defined.
This helped to shorten code and remove some casts

loan method added to Owned base class

---

CMakeLists.txt
examples/CMakeLists.txt
examples/simple/universal/CMakeLists.txt
examples/simple/zenohc/CMakeLists.txt
examples/simple/zenohpico/CMakeLists.txt
install/CMakeLists.txt

Minimum required CMake version reduced to 3.16 to not require users to update CMake on Ubuntu 20.04

cmake min ver reduced to 3.16

---

docs/keyexpr.rst
include/zenohcxx/api.hxx
include/zenohcxx/impl.hxx
tests/universal/keyexpr.cxx

proposed fix for https://github.com/eclipse-zenoh/zenoh-cpp/issues/63

make keyexpr functions standalone

---

cmake/helpers.cmake
docs/keyexpr.rst
examples/CMakeLists.txt
include/zenohcxx/api.hxx
include/zenohcxx/base.hxx
include/zenohcxx/impl.hxx
tests/CMakeLists.txt
tests/universal/keyexpr.cxx

Fix fox issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/20:
- keyexpr compare funciton without error check disallowed for zenohpico as they can provide false results
- keyexpr compare functions with automatic resolving of session declared keyexprs added to `Session` class

forbid use of keyexpr compare funcitons without error check for zenohpico, session-based comared functions added

---

examples/universal/z_pub.cxx
examples/universal/z_sub.cxx
include/zenohcxx/api.hxx
include/zenohcxx/impl.hxx

Added methods wrapping zenoh-c functions `z_publisher_keyexpr` and `z_subscriber_keyexpr`.
Note that these functions exists in zenoh-c only. Should we implement them in zehoh-pico too?

get_keyexpr method for publisher and subscriber

---

examples/CMakeLists.txt
include/zenohcxx/impl.hxx
include/zenohpico.hxx
tests/CMakeLists.txt
tests/build/warnings.cxx

followup to https://github.com/eclipse-zenoh/zenoh-cpp/issues/71

old style type cast warning fixed

---

examples/universal/z_get_attachment.cxx
examples/universal/z_pub_attachment.cxx
examples/universal/z_put.cxx
examples/universal/z_queryable_attachment.cxx
examples/universal/z_sub_attachment.cxx
include/zenohcxx/api.hxx
include/zenohcxx/impl.hxx
tests/zenohc/attachment.cxx

Implement [attachment api](https://github.com/eclipse-zenoh/zenoh/pull/613) support "C++" binding
Currently only for [zeno-c](https://github.com/eclipse-zenoh/zenoh-c/pull/203), zenoh-pico support will coming soon.
Allows add attachment to pub/sub/query/reply.
Adds AttachmentView class with tests (attachment.cxx)
Adds examples:
- z_get_attachment.cxx
- z_pub_attachment.cxx
- z_queryable_attachment.cxx
- z_sub_attachment.cxx

Attachment support implementation

---

examples/universal/z_sub_thr.cxx

This fixes throughput test using system time instead of wall time, which is what we want.

Use wall time in throughput test

---

examples/simple/universal/CMakeLists.txt
examples/simple/zenohc/CMakeLists.txt
examples/simple/zenohpico/CMakeLists.txt

Fix compilation failure in example because of takinh master branch by default.
It seems reasonable to completely remove `master` branch in zenoh projects, this causes error because `master` is selected by default by some tools, like `FetchContent_declare` in CMake

main branch reference added to examples, misprint in pico example fixed

---

.github/workflows/ci.yml

This way we can manually trigger the workflow when needed

fix: Add workflow_dispatch trigger to ci workflow

---

.github/workflows/ci.yml

artifacts actions v3 are deprecated

chore: Update artifacts action to v4

---

include/zenoh/api.hxx
include/zenoh/internal.hxx

Use std::optional for optional arguments in options;
Update options docs;

Use std::optional for optional arguments in options

---

CMakeLists.txt

As per https://github.com/eclipse-zenoh/zenoh-c/pull/466, align how we configure zenoh CMake based projects version.

Align version with zenoh-c

---

CMakeLists.txt

Cherry-pick changes from main into dev/1.0.0
As per https://github.com/eclipse-zenoh/zenoh-c/pull/466, align how we configure zenoh CMake based projects version.

Cmake fixes dev 1.0.0

---

include/zenoh/api/source_info.hxx

remove EntityGlobalIdConstructor since it is no longer exposed in zenoh-c

remove EntityGlobalIdConstructor since it is no longer exposed in zenoh-c

---

include/zenoh/api/bytes.hxx

add missing inline to Bytes::iter() method

add missing inline to Bytes::iter method

---

examples/simple/zenohc/zc_simple.cxx
examples/simple/zenohpico/zp_simple.cxx
include/zenoh/api/base.hxx
include/zenoh/api/bytes.hxx
include/zenoh/api/hello.hxx
include/zenoh/api/keyexpr.hxx
include/zenoh/api/session.hxx
include/zenoh/api/timestamp.hxx
tests/universal/network/implicit.cxx
tests/universal/network/keyexpr.cxx

added  converting constructors from const char* and std::string for KeyExpr;
added converting constructors for Bytes;
Closes #155. Closes #156.

Allow implicit construction for KeyExpr and Bytes

---

examples/universal/z_pub.cxx

Somewhere along the road, the PublisherPutOptions was forgotten in one of the examples.
I thought it did not look good, and I felt bad for the mission option.
So now I included it in the "put", which I think was the original intention.

Adding missing options to put

---

install/CMakeLists.txt

Fix provided by @btertoolen in https://github.com/eclipse-zenoh/zenoh-cpp/pull/137. Thanks for your contribution!

fix: use debian compatible arch

---

install/CMakeLists.txt

The architecture in the Debian packages in the Github releases is x86_64, which is not a valid Debian architecture:
`➜ sudo dpkg -i packages/zenoh-cpp-0.11.0.0.deb
dpkg: warning: parsing file '/var/lib/dpkg/tmp.ci/control' near line 1:
'x86_64' is not a valid architecture name in 'Architecture' field: character '_' not allowed (only letters, digits and characters '-')
dpkg: error processing archive packages/zenoh-cpp-0.11.0.0.deb (--install):
package architecture (x86_64) does not match system (amd64)
Errors were encountered while processing:
packages/zenoh-cpp-0.11.0.0.deb`
See also https://wiki.debian.org/SupportedArchitectures
Instead using dpkg --print-architecture (or any other way if you dont want to have a dependency on dpkg) to determine the architecture provides the correct …

Determine debian architecture using dpkg

---

install/CMakeLists.txt

Reverts eclipse-zenoh/zenoh-cpp#161 to allow integrating #137

Revert "fix: use debian compatible arch"

---

ci/scripts/build.bash

On 0d77925bc92a2313d27a86f82d4067b92f729591 the build procedure for zenoh-cpp was updated so this needs to be updated as well.

fix: update ci build script

---

examples/universal/z_get_attachment.cxx
examples/universal/z_queryable.cxx
examples/universal/z_queryable_attachment.cxx
examples/universal/z_sub_attachment.cxx
examples/zenohc/z_queryable_shm.cxx
include/zenoh/api/config.hxx
include/zenoh/api/encoding.hxx
include/zenoh/api/query.hxx
include/zenoh/api/sample.hxx
include/zenoh/api/session.hxx
tests/universal/network/implicit.cxx
tests/universal/network/queryable_get.cxx

bump zenoh-c version;
add congestion_control, priority and is_express to GetOptions; 
add default encoding support in publisher options for ZENOH-C; 
add Encoding copy constructor and assignment;
add Config::from_env constructor;
add Encoding::set_schema for ZENOH-C;
fix examples to account for missing query payload;

Align with zenoh-c/pico

---

examples/universal/z_ping.cxx
examples/universal/z_pub_thr.cxx
examples/universal/z_sub.cxx
examples/universal/z_sub_thr.cxx
examples/zenohc/z_ping_shm.cxx
examples/zenohc/z_pub_shm_thr.cxx
examples/zenohc/z_queryable_shm.cxx
examples/zenohc/z_sub_liveliness.cxx
examples/zenohc/z_sub_shm.cxx
include/zenoh/api/bytes.hxx
include/zenoh/api/closures.hxx
include/zenoh/api/scout.hxx
include/zenoh/api/session.hxx
include/zenoh/detail/closures.hxx
tests/universal/bytes.cxx

bump zenoh-c and zenoh-pico versions;
align serialization - i.e remove serializaiton by aliasing and add data-consuming serializaiton methods;
aliasing serialization is implemented for shared_ptr;
fixed all methods accepting callable to impose copy if callable is passed by reference (Closes #158)

align serialization with zenoh-c and zenoh-pico

---

tests/universal/network/pub_sub.cxx

reintroduce 2 session pub-sub pico test;
Bump zenoh-c/pico versions;

reintroduce 2 session pub-sub pico test

---

examples/universal/z_get.cxx
examples/universal/z_get_attachment.cxx
examples/universal/z_get_channel.cxx
examples/universal/z_get_channel_non_blocking.cxx
examples/universal/z_pub.cxx
examples/universal/z_pub_attachment.cxx
examples/universal/z_pub_thr.cxx
examples/universal/z_put.cxx
examples/universal/z_queryable.cxx
examples/universal/z_queryable_attachment.cxx
include/zenoh/api/bytes.hxx
include/zenoh/api/closures.hxx

* Removed extraneous semicolons to solve q++ compilation errors.
* Changed test for C++ designated initializers to check for language feature support rather than C++ version to solve q++ compilation errors.
Closes #195.

Support for the QNX 7.1.0 qcc compiler

---

include/zenoh/api/enums.hxx
include/zenoh/api/session.hxx
include/zenoh/zenohc.hxx
scripts/install_from_git.sh
scripts/install_from_local.sh

move reliability to publisher;
bump zenoh-c/pico submodules;
make scripts build pico with unstable features support; 
properly account for pico unstable features;
Closes #203

Move reliability to publisher

---

include/zenoh/api/enums.hxx
include/zenoh/api/hello.hxx
include/zenoh/api/id.hxx
include/zenoh/api/keyexpr.hxx
include/zenoh/api/liveliness.hxx
include/zenoh/api/publisher.hxx
include/zenoh/api/query.hxx
include/zenoh/api/reply.hxx
include/zenoh/api/sample.hxx
include/zenoh/api/session.hxx
include/zenoh/api/shm/buffer/zshm.hxx
include/zenoh/api/shm/buffer/zshmmut.hxx
include/zenoh/api/shm/client/shm_client.hxx
include/zenoh/api/shm/client/shm_segment.hxx
include/zenoh/api/shm/client_storage/client_storage.hxx
include/zenoh/api/shm/protocol_implementations/posix/posix_shm_client.hxx
include/zenoh/api/shm/protocol_implementations/posix/posix_shm_provider.hxx
include/zenoh/api/shm/provider/alloc_layout.hxx
include/zenoh/api/shm/provider/chunk.hxx
include/zenoh/api/shm/provider/shm_provider.hxx
include/zenoh/api/shm/provider/types.hxx
include/zenoh/api/source_info.hxx
include/zenoh/api/timestamp.hxx

mark unstable features in the docs

mark unstable features in the docs

---

include/zenoh/api/config.hxx
tests/zenohc/config.cxx

remove Config::client() and ::peer() methods

remove Config::client() and ::peer() methods

---

include/zenoh/api/hello.hxx
include/zenoh/api/id.hxx
include/zenoh/api/publisher.hxx
include/zenoh/api/queryable.hxx
include/zenoh/api/session.hxx
include/zenoh/api/subscriber.hxx
tests/universal/network/pub_sub.cxx
tests/universal/network/queryable_get.cxx

added support for z_hello_clone;
added support for background declarations;
added support for z_id_t to string;
added support for session_close_options;

api alignment

---

include/zenoh/api/bytes.hxx

update docs regarding undefined behavior when using multiple Bytes::Writers

update docs regarding undefined behavior when using multiple Bytes::Writers

---

examples/universal/z_delete.cxx
examples/universal/z_get.cxx
examples/universal/z_get_channel.cxx
examples/universal/z_get_channel_non_blocking.cxx
examples/universal/z_info.cxx
examples/universal/z_pub.cxx
examples/universal/z_pub_delete.cxx
examples/universal/z_pub_thr.cxx
examples/universal/z_put.cxx
examples/universal/z_queryable.cxx
examples/universal/z_scout.cxx
examples/universal/z_sub.cxx
examples/universal/z_sub_thr.cxx
examples/zenohc/z_get_liveliness.cxx
examples/zenohc/z_get_shm.cxx
examples/zenohc/z_liveliness.cxx
examples/zenohc/z_pub_shm.cxx
examples/zenohc/z_pub_shm_thr.cxx
examples/zenohc/z_queryable_shm.cxx
examples/zenohc/z_sub_liveliness.cxx
examples/zenohc/z_sub_shm.cxx
include/zenoh/api/config.hxx
include/zenoh/api/hello.hxx
tests/zenohc/config.cxx

- Rename z_hello_locators to zp_hello_locators (https://github.com/eclipse-zenoh/zenoh-pico/pull/677)
- Rename zc_config_insert_json to zc_config_insert_json5 (https://github.com/eclipse-zenoh/zenoh-c/pull/698)
Closes: https://github.com/eclipse-zenoh/zenoh-c/issues/693

Align renamed API calls

---

docs/Doxyfile
examples/universal/z_info.cxx
examples/universal/z_scout.cxx
examples/zenohc/z_sub_shm.cxx
include/zenoh/api.hxx
include/zenoh/api/bytes.hxx
include/zenoh/api/enums.hxx
include/zenoh/api/hello.hxx
include/zenoh/api/keyexpr.hxx
include/zenoh/api/publisher.hxx
include/zenoh/api/query.hxx
include/zenoh/api/reply.hxx
include/zenoh/api/sample.hxx
include/zenoh/api/session.hxx
include/zenoh/api/source_info.hxx
include/zenoh/api/timestamp.hxx
include/zenoh/detail/closures_concrete.hxx
include/zenoh/zenohc.hxx
tests/universal/network/pub_sub.cxx

prepend feature macros with Z_FEATURE to avoid name collisions

prepend feature macros with Z_FEATURE to avoid name collisions

---

include/zenoh/api/ext/serialization.hxx

`serialization.hxx` is missing `#pragma once`

[Fix] Add missing pragma once

---

.github/workflows/ci.yml

print clang-format version in ci;
hardcode ubuntu24.04 as runner for running clang-format job, to avoid unexpected clang-format version changes.

fix clang-fromat runner to ubuntu24.04 and print clang-format version in ci

---

.github/workflows/release.yml

As per eclipse-zenoh/.eclipsefdn#18, secrets were updated to follow eclipse foundation naming convention.

chore: update org secrets

---

.github/workflows/release.yml

Adds support to release libzenohcpp to homebrew. Requires https://github.com/eclipse-zenoh/homebrew-zenoh/pull/13

feat: add job to release libzenohcpp to homebrew

---

scripts/install_from_git.sh

Not all shells support "if ()", changed to "if []"
Also for consistency with the rest of the script.

Script shell compatibility fix

---

include/zenoh/api/reply.hxx

Add clone method to Reply
Required here https://github.com/ros2/rmw_zenoh/pull/311/files

Add clone method to Reply

---

.github/workflows/release.yml

Tested here: https://github.com/eclipse-zenoh/zenoh-cpp/actions/runs/12157330553/job/33902933400

Fix homebrew publish

---

.github/workflows/ci.yml

Add ci status check to main CI workflow so branch protection rule can verify all requirements are done before merging.

fix: add ci status check

---

examples/CMakeLists.txt

fix liveliness examples not being built for zenoh-pico if zenoh-c is disabled

fix liveliness examples not being built for zenoh-pico if zenoh-c is disabled

---

.github/workflows/ci.yml
.markdownlint.yaml
README.md
docs/README.md

As https://github.com/eclipse-zenoh/zenoh/issues/1666, fix the README.md format and update CI.

Add CI for checking markdown format.

---

include/zenoh/api/bytes.hxx
tests/universal/bytes.cxx

add support for transferring data ownership to Bytes via custom deleter

add support for transferring data ownership to Bytes via custom deleter

---

include/zenoh/api/bytes.hxx

add Bytes::get_contiguous_view method

add Bytes::get_contiguous_view method to allow getting a contiguous view to zenoh::Bytes data in case it is non-fragmented

---

include/zenoh/api/ext/publication_cache.hxx

add missing inlines to declare_publication_cache implementations

add missing inlines to declare_publication_cache implementations

---

include/zenoh/api/ext/advanced_subscriber.hxx
include/zenoh/api/subscriber.hxx

add zenoh::Subscriber::get_id() method;
add zenoh::ext::AdvancedSubscriber::get_keyexpr() method;
add zenoh::ext::AdvancedSubscriber::get_id() method;

add missing subscriber methods

---

.github/workflows/ci.yml

remove unneeded command from ci (since cmake is already invoked in the build directory by install_from_git.sh)
closes #333

remove unneeded command from ci

---

include/zenoh/api/shm/buffer/zshm.hxx

Related with this issue in rmw_zenoh_cpp https://github.com/ros2/rmw_zenoh/issues/350 when building in ubuntu 20.04

Addes missing include to zshm

---

include/zenoh/api/session.hxx

In zenoh rust we have u64 timeout

Fix liveliness timeout type

---

include/zenoh/api/session.hxx

This PR sets the same default reliability value as zenoh rust.

fix: align the default value of reliability

---

include/zenoh/api/bytes.hxx
tests/universal/bytes.cxx

merge from connoranderson:connor/fix_str_tmp_conversion (#345)

fix std::string&& to zenoh::Bytes conversion to use proper string length instead of null-terminator

---

examples/zenohc/z_advanced_pub.cxx
examples/zenohc/z_advanced_sub.cxx
include/zenoh/api/ext/session_ext.hxx

align advanced pub-sub with zenoh-c;
bump zenoh-c;
bump zenoh-pico;

align advanced pub-sub with zenoh-c

---

examples/zenohc/z_advanced_sub.cxx
include/zenoh/api/ext/session_ext.hxx

support for default recovery option without last sample miss detection (i.e. without heartbeat nor periodic queries from subscriber's side)

support for default recovery option without last sample miss detection

---

include/zenoh/api/session.hxx

Mark liveliness_declare_background_subscriber as stable and enable it for zenoh-pico
Related to:
https://github.com/eclipse-zenoh/zenoh-c/pull/894
https://github.com/eclipse-zenoh/zenoh-pico/pull/854

Mark liveliness_declare_background_subscriber as stable and enable it for zenoh-pico

---

CMakeLists.txt

Using zenoh-cpp in a project, having built and installed zenoh-c (1.0.0) I came across a build error from zenoh-cpp, it looked like this:
```
...
CMake Error at zenoh-cpp/cmake/helpers.cmake:103 (add_custom_command):
Error evaluating generator expression:
$<TARGET_RUNTIME_DLLS:warnings_zenohc>
Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
zenoh-cpp/tests/CMakeLists.txt:39 (copy_dlls)
zenoh-cpp/tests/CMakeLists.txt:105 (add_test_instance)
...
```
this, but with multiple more of the same error.
The error itself is not my main problem, I overcame that problem by simply commenting out the add_subdirectory(..) for examples and tests. 
But the reason for this PR is because I, and others, only use zenoh-cpp as a library in my project, so I don't …

Conditionally build examples and tests

---

examples/universal/z_pub.cxx
examples/universal/z_querier.cxx
include/zenoh/api/ext/advanced_publisher.hxx
include/zenoh/api/matching.hxx
include/zenoh/api/publisher.hxx
include/zenoh/api/querier.hxx

Add Zenoh-Pico matching support and rename Zenoh-C methods from `zc_*` to `z_*`
Related PRs:
https://github.com/eclipse-zenoh/zenoh-pico/pull/862
https://github.com/eclipse-zenoh/zenoh-pico/pull/853
https://github.com/eclipse-zenoh/zenoh-c/pull/898

Add Zenoh-Pico matching support and rename Zenoh-C methods

---

include/zenoh/api/base.hxx
include/zenoh/api/channels.hxx
include/zenoh/api/hello.hxx
include/zenoh/api/interop.hxx
include/zenoh/api/keyexpr.hxx
include/zenoh/api/liveliness.hxx
include/zenoh/api/query.hxx
include/zenoh/api/reply.hxx
include/zenoh/api/sample.hxx

Move constructor validates that loan mut doesn't return nullptr: this may happen if trying to move from null value.
Channel code corrected to ensure that null object not passed to loan function

liveliness crash fix

---

.github/workflows/ci.yml
include/zenoh/api/base.hxx
include/zenoh/api/channels.hxx
include/zenoh/api/hello.hxx
include/zenoh/api/interop.hxx
include/zenoh/api/keyexpr.hxx
include/zenoh/api/liveliness.hxx
include/zenoh/api/query.hxx
include/zenoh/api/reply.hxx
include/zenoh/api/sample.hxx
scripts/install_from_git.sh
scripts/install_from_local.sh
scripts/install_local.sh

Fix std::move operation for owned objects in null state.
Update ci to run tests in debug mode to catch related bugs in the future based on #430 .

Fix std::move operation for owned objects in null state

---

examples/getargs.hxx
examples/universal/z_pong.cxx

allow positional arguments to be interleaved with named ones;
fix message in z_pong example;

examples: allow positional arguments to be interleaved with named ones

---

CMakeLists.txt

By checking if the target actually exists before calling `FindPackage`, it is possible to either use `zenohc` and `zenohcxx` as a submodule in a project or add the projects via cmake's `FetchContent` mechanism.
The following works for me:
```cmake
include(FetchContent)
FetchContent_Declare(
zenohc
GIT_REPOSITORY https://github.com/oleid/zenoh-c.git
GIT_TAG fix/CMP0111
DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)
FetchContent_Declare(
zenohcxx
GIT_REPOSITORY https://github.com/oleid/zenoh-cpp.git
GIT_TAG feature/allow_submodule_build
DOWNLOAD_EXTRACT_TIMESTAMP TRUE
)
FetchContent_MakeAvailable(zenohc zenohcxx)
```

Allow using zenohc as submodule

---

.github/workflows/ci.yml
include/zenoh/api/querier.hxx
include/zenoh/api/query.hxx
include/zenoh/api/session.hxx

fix ci to pass switches in upper-case;
remove source info from query/reply for zenoh-pico;

fix zenoh-pico ci

---

.github/workflows/ci.yml

On macos-15 LAN access is required but the regular gh runner user doesn't have permission. Workaround by running as root.
See https://github.com/actions/runner-images/issues/10924

ci: run ctest with sudo to avoid permission error

---

docs/queryable.rst

fix queryable example in docs

---

include/zenoh/api/keyexpr.hxx

The KeyExpression#as_string_view API is not visible in the official documentation - I believe due to missing empty line.
See https://zenoh-cpp.readthedocs.io/en/latest/keyexpr.html# and the screenshot:

KeyExpression#as_string_view documentation Fix
