eclipse-zenoh/zenoh-cpp

- CMakeLists.txt
https://github.com/eclipse-zenoh/zenoh-cpp/issues/7
> cmake version changed to 3.16

- README.md
Readme update related to issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/7
> added recommendation not to use relative path

- include/zenohcpp_structs.h
> typedefs for zenoh-c enums added

- include/zenohcpp_structs.h
- tests/options.cpp
Setters, getters, compare operations, default constructors, tests for this.
Closes issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/12
> cover options structures in C++ api

- examples/c/z_queryable.c
- examples/cpp/z_queryable.cpp
- examples/cpp/z_sub_thr.cpp
- include/zenohcpp_objects.h
- include/zenohcpp_structs.h
- tests/keyexpr.cpp
> Several missing zenoh-c functions added

- examples/cpp/z_scout.cpp
- include/zenohcpp_objects.h
- include/zenohcpp_structs.h
- tests/config.cpp
> functions z_config_client, zc_init_logger covered

- include/zenohcpp_objects.h
- tests/config.cpp
- config_peer
- config_from_str
- config_from_file
> covered config functions

- CMakeLists.txt
- examples/c/z_get.c
- examples/c/z_non_blocking_get.c
- examples/c/z_pull.c
- examples/c/z_queryable.c
- examples/c/z_sub.c
- include/zenohcpp_objects.h
- include/zenohcpp_structs.h
Updated zenoh-cpp accordingly to recent fix in zenoh-c https://github.com/eclipse-zenoh/zenoh-c/issues/91
> updated to zenoh-c api change - add z_owned_str_t

- examples/universal/z_get.cxx
updated z_get example accordingly to issue https://github.com/eclipse-zenoh/zenoh-c/issues/146
> added value parameter to z_get example

- .github/workflows/release.yml
Added empty release.yml to test release process in branches
> empty release.yml

- examples/universal/z_get.cxx
- include/zenohcxx/api.hxx
- tests/universal/options.cxx
API update accordingly to 
https://github.com/eclipse-zenoh/zenoh-c/pull/151
https://github.com/eclipse-zenoh/zenoh-pico/pull/211
> replace with_value to value

- examples/simple/universal/z_simple.cxx
- include/zenohcxx/api.hxx
- tests/universal/keyexpr.cxx
fix for https://github.com/eclipse-zenoh/zenoh-cpp/issues/49
> const std::string& in KeyExprView

- CMakeLists.txt
- install/CMakeLists.txt
Bump version from 0.7.0.1 to 0.7.2.1
> Bump version to 0.7.2.0

- examples/CMakeLists.txt
- examples/universal/z_ping.cxx
- examples/universal/z_pub.cxx
- examples/zenohc/z_get_channel_non_blocking.cxx
- include/zenoh.hxx
- include/zenohcxx/api.hxx
- include/zenohcxx/base.hxx
- include/zenohcxx/impl.hxx
solves issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/5 from zenoh-cpp side. To make full fix the zenoh-pico should be corrected to compile under windows
> fixes to compile with MSVC

- examples/simple/universal/z_simple.cxx
fix for https://github.com/eclipse-zenoh/zenoh-cpp/issues/51
> removed session instance from sample class

- examples/getargs.h
- examples/universal/z_delete.cxx
- examples/universal/z_get.cxx
- examples/universal/z_info.cxx
- examples/universal/z_pub.cxx
- examples/universal/z_pub_delete.cxx
- examples/universal/z_pub_thr.cxx
- examples/universal/z_pull.cxx
- examples/universal/z_put.cxx
- examples/universal/z_queryable.cxx
- examples/universal/z_scout.cxx
- examples/universal/z_sub.cxx
- examples/universal/z_sub_thr.cxx
Fix for issue https://github.com/eclipse-zenoh/zenoh-cpp/issues/74
> config file parameter for examples

- docs/pubsub.rst
> sample in documemntation fix

- include/zenohcxx/api.hxx
- include/zenohcxx/impl.hxx
Taken bugfix part only from https://github.com/eclipse-zenoh/zenoh-cpp/pull/87
Fixes issue https://github.com/eclipse-zenoh/roadmap/discussions/105
> fixed missing 'inline's

- include/zenohcxx/api.hxx
Add support for qos settings in sample (see https://github.com/eclipse-zenoh/zenoh/pull/730)
> Add support for qos settings in sample

- include/zenoh/api/bytes.hxx
- include/zenoh/detail/closures.hxx
- include/zenoh/detail/closures_concrete.hxx
- tests/universal/bytes.cxx
add support for deque, set, unordered_set, map
fix template arguments for vector and unordered map
make Bytes::Iterator return std::optional<Bytes>
> add support for more stl containers serialization/ deserialization

- include/zenoh/api/publisher.hxx
based on https://github.com/eclipse-zenoh/zenoh/pull/1124
> remove publisher set methods

- include/zenoh/api/bytes.hxx
- include/zenoh/api/publisher.hxx
- include/zenoh/api/reply.hxx
Compatibility with zenoh-c PRs #448, #449, #463.
> zenoh-c compatibility

- examples/universal/z_get_attachment.cxx
- include/zenoh/api/base.hxx
- include/zenoh/api/publisher.hxx
- include/zenoh/api/query.hxx
- include/zenoh/api/reply.hxx
- include/zenoh/api/sample.hxx
- include/zenoh/api/subscriber.hxx
remove unnecessary decltype(auto) and replace it with explicit types.
> remove unnecessary decltype(auto)

- include/zenoh/api/channels.hxx
- tests/universal/network/pub_sub.cxx
Fix ring channel and add pub/sub test using a ring channel.
> Fix ring channel

- examples/universal/z_get.cxx
> fix z_get example

- examples/zenohc/z_get_shm.cxx
- examples/zenohc/z_liveliness.cxx
- examples/zenohc/z_ping_shm.cxx
- examples/zenohc/z_pub_shm.cxx
- examples/zenohc/z_pub_shm_thr.cxx
- examples/zenohc/z_queryable_shm.cxx
- examples/zenohc/z_sub_liveliness.cxx
- examples/zenohc/z_sub_shm.cxx
> Align SHM examples

- include/zenoh/api/encoding.hxx
- include/zenoh/api/sample.hxx
reintroduce encdoing move shadowed by pr #166.
> reintroduce encdoing move shadowed by pr #166

- examples/universal/z_ping.cxx
- examples/universal/z_pub_thr.cxx
- examples/universal/z_sub.cxx
- examples/universal/z_sub_thr.cxx
- examples/zenohc/z_ping_shm.cxx
- examples/zenohc/z_pub_shm_thr.cxx
- examples/zenohc/z_queryable_shm.cxx
- examples/zenohc/z_sub_liveliness.cxx
- examples/zenohc/z_sub_shm.cxx
- include/zenoh/api/bytes.hxx
- include/zenoh/api/closures.hxx
- include/zenoh/api/scout.hxx
- include/zenoh/api/session.hxx
- include/zenoh/detail/closures.hxx
- tests/universal/bytes.cxx
Reverts eclipse-zenoh/zenoh-cpp#169
By request of @DenisBiryukov91 temporary revering to make possible to merge other requests based on original state of tree
> Revert "align serialization with zenoh-c and zenoh-pico"

- examples/universal/z_ping.cxx
- examples/universal/z_pub_thr.cxx
- examples/universal/z_sub.cxx
- examples/universal/z_sub_thr.cxx
- examples/zenohc/z_ping_shm.cxx
- examples/zenohc/z_pub_shm_thr.cxx
- examples/zenohc/z_queryable_shm.cxx
- examples/zenohc/z_sub_liveliness.cxx
- examples/zenohc/z_sub_shm.cxx
- include/zenoh/api/bytes.hxx
- include/zenoh/api/closures.hxx
- include/zenoh/api/scout.hxx
- include/zenoh/api/session.hxx
- include/zenoh/detail/closures.hxx
- include/zenoh/detail/commons.hxx
- tests/universal/bytes.cxx
bump zenoh-c and zenoh-pico versions;
align serialization - i.e remove serializaiton by aliasing and add data-consuming serializaiton methods;
aliasing serialization is implemented for shared_ptr;
fixed all methods accepting callable to impose copy if callable is passed by reference (Closes https://github.com/eclipse-zenoh/zenoh-cpp/issues/158)
> align serialization with zenoh-c and zenoh-pico

- include/zenoh/api/encoding.hxx
- include/zenoh/api/session.hxx
add encoding set_schema method support for zenoh-pico;
add default encoding support for publisher for zenoh-pico;
> update encoding support for zenoh-pico;

- .github/workflows/ci.yml
- .github/workflows/release.yml
- install/PackageConfig.cmake.in
> merge main

- include/zenoh/api/bytes.hxx
- include/zenoh/api/config.hxx
- include/zenoh/api/keyexpr.hxx
- include/zenoh/api/liveliness.hxx
- include/zenoh/api/publisher.hxx
- include/zenoh/api/query.hxx
- include/zenoh/api/session.hxx
- include/zenoh/api/shm/client_storage/client_storage.hxx
- include/zenoh/api/shm/protocol_implementations/posix/posix_shm_provider.hxx
- include/zenoh/api/shm/provider/types.hxx
> fix err argument name in docs

- tests/CMakeLists.txt
> Merge dev/1.0.0 into main

- include/zenoh/api/sample.hxx
- include/zenoh/api/session.hxx
add missing reliability options for delete operation and reliability sample accessor
> add missing reliability options for delete operation and reliability sample accessor

- include/zenoh/api/enums.hxx
move Reliability enum under unstable
> move Reliability enum under unstable

- include/zenoh/api/session.hxx
> liveliness history support

- include/zenoh/api/interop.hxx
- include/zenoh/api/scout.hxx
- include/zenoh/api/session.hxx
- include/zenoh/detail/closures_concrete.hxx
- tests/universal/network/pub_sub.cxx
- tests/universal/network/queryable_get.cxx
support for mutable references in callbacks;
enable background undeclare tests for pico;
> Align with zenoh-c/pico

- include/zenoh/api/bytes.hxx
add slice iterator api for Bytes
> add slice iterator api for Bytes

- include/zenoh/api/source_info.hxx
To be merged after https://github.com/eclipse-zenoh/zenoh-c/pull/694
Original PR: https://github.com/eclipse-zenoh/zenoh-cpp/pull/219
> SourceSn is uint32_t and not uint64_t

- include/zenoh/api/encoding.hxx
add equality relation for encoding
> add equality relation for encoding

- README.md
clarify readme regarding installation prerequisites
> clarify readme regarding installation prerequisites

- examples/getargs.h
- examples/universal/z_delete.cxx
- examples/universal/z_get.cxx
- examples/universal/z_get_attachment.cxx
- examples/universal/z_get_channel.cxx
- examples/universal/z_get_channel_non_blocking.cxx
- examples/universal/z_info.cxx
- examples/universal/z_ping.cxx
- examples/universal/z_pong.cxx
- examples/universal/z_pub.cxx
- examples/universal/z_pub_attachment.cxx
- examples/universal/z_pub_delete.cxx
- examples/universal/z_pub_thr.cxx
- examples/universal/z_put.cxx
- examples/universal/z_queryable.cxx
- examples/universal/z_queryable_attachment.cxx
- examples/universal/z_scout.cxx
- examples/universal/z_sub.cxx
- examples/universal/z_sub_attachment.cxx
- examples/universal/z_sub_thr.cxx
- examples/zenohc/z_get_liveliness.cxx
- examples/zenohc/z_get_shm.cxx
- examples/zenohc/z_liveliness.cxx
- examples/zenohc/z_ping_shm.cxx
- examples/zenohc/z_pub_shm.cxx
- examples/zenohc/z_pub_shm_thr.cxx
- examples/zenohc/z_queryable_shm.cxx
- examples/zenohc/z_sub_liveliness.cxx
- examples/zenohc/z_sub_shm.cxx
support for peer mode in zenoh-pico examples;
cleanup of cmd argument parsing for examples;
Closes #105.
> support for peer mode in zenoh-pico examples

- include/zenoh/api/ext/serialization.hxx
- tests/universal/serialization.cxx
serialziation support for bool
> serialziation support for bool

- include/zenoh/api/publisher.hxx
- include/zenoh/api/queryable.hxx
- include/zenoh/api/session.hxx
- include/zenoh/api/subscriber.hxx
account for api changesi n zenoh-c/pico;
reintroduce undeclare methods;
> Api alignment 2

- README.md
- include/zenoh.hxx
clarify library requirements regarding C++17 compiler.
Closes #235.
> clarify library requirements regarding C++17 compiler

- tests/universal/serialization.cxx
> add serialization format test

- install/cpack_project_config.cmake
set deb and rpm packages architecture to all/noarch
> set deb and rpm packages architecture to all/noarch

- examples/getargs.h
- examples/universal/z_pub.cxx
- examples/zenohc/z_pub_shm.cxx
- include/zenoh/api/base.hxx
- include/zenoh/api/publisher.hxx
added matching status and matching listener support
> added matching status and matching listener support

- include/zenoh/api/session.hxx
add Session::is_closed method;
closes #280.
> add Session::is_closed method

- examples/getargs.hxx
- examples/universal/z_pub_thr.cxx
added support for --cfg option;
added support for parsing --opt=value;
fixed priority parsing in z_pub_thr;
> fix cli argument parsing in examples

- README.md
- examples/README.md
- examples/universal/z_storage.cxx
- examples/universal/z_sub_thr.cxx
- include/zenoh/api/config.hxx
- include/zenoh/api/keyexpr.hxx
add z_storage_example;
add KeyExpr copy constructor and assignment;
update readme;
> Align examples and api with Zenoh-rust.

- include/zenoh/api/ext/session_ext.hxx
- include/zenoh/api/query.hxx
- include/zenoh/api/session.hxx
Follow-up of https://github.com/eclipse-zenoh/zenoh-c/pull/913 and https://github.com/eclipse-zenoh/zenoh-pico/pull/894.
> Adopt the different congestion control defaults as in Rust

- docs/pubsub.rst
- examples/universal/z_get_channel_non_blocking.cxx
- tests/universal/network/liveliness.cxx
- tests/universal/network/pub_sub.cxx
- tests/universal/network/queryable_get.cxx
- tests/zenohc/shm_api.cxx
> add missing <chrono> includes

- include/zenoh/api/session.hxx
add support for allowed_origin Queryable option
> add support for allowed_origin Queryable option

- include/zenoh/api/ext/session_ext.hxx
Sister PR to account for API changes due to https://github.com/eclipse-zenoh/zenoh/pull/1792
> support for api changes due to namespaces

- examples/zenohc/z_advanced_pub.cxx
- include/zenoh/api/ext/session_ext.hxx
- zenoh-c-branch.txt
Support for sporadic heartbeat introduced in
https://github.com/eclipse-zenoh/zenoh/pull/1861
https://github.com/eclipse-zenoh/zenoh-c/pull/969
> heartbeat mode support

- examples/zenohc/z_advanced_sub.cxx
- include/zenoh/api/ext/session_ext.hxx
- tests/CMakeLists.txt
- tests/zenohc/advanced_pub_sub.cxx
fix SessionExt::declare_advanced_subscriber for channels;
add advanced pub-sub tests;
> fix SessionExt::declare_advanced_subscriber for channels

- include/zenoh/api/publisher.hxx
- include/zenoh/api/querier.hxx
- include/zenoh/api/queryable.hxx
- include/zenoh/api/source_info.hxx
- tests/universal/network/pub_sub.cxx
- tests/universal/network/queryable_get.cxx
add missing methods for queryable, publisher and querier
> add missing methods for queryable, publisher and querier

- tests/run_with_router.sh
Required for easier debugging of zenoh pico ci issue.
> Add logs of test binaries
